---
fedora_packages: [zsh, curl, rsync, git]
fedora_repo_git: https://pagure.io/forks/kruton/quick-fedora-mirror.git # PR with fixes
fedora_repo_version: ee1f19fd449e6db65e164cd052141836712162e9
fedora_repo_path: /opt/quick-fedora-mirror
fedora_config_file: "{{ fedora_repo_path }}/quick-fedora-mirror.conf"
fedora_job: "{{ fedora_repo_path }}/quick-fedora-mirror"
fedora_rsyncd_modules:
  fedora-enchilada:
    path: "{{ fedora_destd }}/fedora"
    comment: "{{ fedora_comment }}"
  fedora-epel:
    path: "{{ fedora_destd }}/epel"
    comment: "{{ fedora_epel_comment }}"
  fedora-secondary:
    path: "{{ fedora_destd }}/fedora-secondary"
    comment: "{{ fedora_secondary_comment }}"
