---
# Activate directory messages - messages given to remote users when they
# go into a certain directory.
vsftpd_dirmessage_enable: true

# Activate logging of uploads/downloads.
vsftpd_xferlog_enable: true

# Make sure PORT transfer connections originate from port 20 (ftp-data).
vsftpd_connect_from_port_20: true

# You may override where the log file goes if you like. The default is shown
# below.
vsftpd_xferlog_file: /var/log/xferlog

# If you want, you can have your log file in standard ftpd xferlog format.
# Note that the default log file location is /var/log/xferlog in this case.
vsftpd_xferlog_std_format: true

# You may change the default value for timing out an idle session.
vsftpd_idle_session_timeout: 600

# You may change the default value for timing out a data connection.
vsftpd_data_connection_timeout: 120

# You may fully customise the login banner string:
vsftpd_ftpd_banner: "Welcome to {{ ansible_fqdn }}!"

# When "listen" directive is enabled, vsftpd runs in standalone mode and
# listens on IPv4 sockets. This directive cannot be used in conjunction
# with the listen_ipv6 directive.
vsftpd_listen: false

# This directive enables listening on IPv6 sockets. By default, listening
# on the IPv6 "any" address (::) will accept connections from both IPv6
# and IPv4 clients. It is not necessary to listen on *both* IPv4 and IPv6
# sockets. If you want that (perhaps because you want to listen on specific
# addresses) then you must run two copies of vsftpd with two configuration
# files.
# Make sure, that one of the listen options is commented !!
vsftpd_listen_ipv6: true

# If enabled, vsftpd will display directory listings with the time
# in  your  local  time  zone.  The default is to display GMT. The
# times returned by the MDTM FTP command are also affected by this
# option.
vsftpd_use_localtime: true

# This option specifies the location of the RSA certificate to use for SSL
# encrypted connections.
# vsftpd_rsa_cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
# vsftpd_rsa_private_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
vsftpd_ssl_enable: false

vsftpd_pasv_enable: false

# The maximum port to allocate for PASV style data connections.
# Can be used to specify a narrow port range to assist firewalling.
vsftpd_pasv_max_port: 0

# The minimum port to allocate for PASV style data connections.
# Can be used to specify a narrow port range to assist firewalling.
vsftpd_pasv_min_port: 0
