---
debian_archive: true
debian_archive_to: "{{ lcmirror_root }}/debian"
debian_archive_mirrorname: "{{ ansible_fqdn }}"
debian_archive_rsync_host: ftp.acc.umu.se
debian_archive_rsync_path: debian
debian_archive_logdir: /var/log/debian
debian_archive_comment: Debian Archive
debian_archive_schedule: "{{ lcmirror_cron_noop }}"

debian_cd: true
debian_cd_logdir: /var/log/debian
debian_cd_source_url: rsync://cdimage.debian.org/debian-cd/
debian_cd_lastupdate_url: https://cdimage.debian.org/debian-cd/project/trace/cdimage.debian.org
debian_cd_lastupdate_file: "$TARGET/project/trace/{{ ansible_fqdn }}"
debian_cd_postscript: curl --clobber -Lo "$LASTUPDATE_FILE" "$LASTUPDATE_URL" >/dev/null
debian_cd_comment: Debian CD images
