---
- name: Install script dependencies
  ansible.builtin.package:
    name: "{{ ubuntu_packages }}"
    state: present

- name: Clone ubumirror repository
  ansible.builtin.git:
    repo: "{{ ubuntu_repo_git }}"
    version: "{{ ubuntu_repo_version }}"
    dest: "{{ ubuntu_repo_path }}"

- name: Template ubumirror.conf
  ansible.builtin.template:
    src: ubumirror.conf.j2
    dest: /etc/ubumirror.conf
    mode: '0644'

- name: Create log directory
  ansible.builtin.file:
    path: "{{ ubuntu_logdir }}"
    owner: "{{ lcmirror_user }}"
    group: "{{ lcmirror_user }}"
    mode: '0755'
    state: directory

- name: Include ubumirrors
  ansible.builtin.include_tasks:
    file: ubumirror.yml
  loop: "{{ ubuntu_mirrors }}"
  loop_control:
    loop_var: ubuntu_mirror
  vars:
    ubumirror: "{{ ubuntu_mirror }}"
  when: lookup("ansible.builtin.vars", "ubuntu_" + ubuntu_mirror)
