---
- name: Deploy Caddyfile and restart service
  hosts: mirrors
  gather_facts: false
  tasks:
    - name: Import config_caddyfile.yml
      ansible.builtin.import_role:
        name: maxhoesel.caddy.caddy_server
        tasks_from: config_caddyfile
