---
lcmirror_root: /srv/mirror

# archlinux_schedule: '0 1 * * *'
# debian_archive_schedule: '0 */6 * * *'
# debian_cd_schedule: '0 2 * * *'
# freebsd_schedule: '0 */3 * * *'
# mxlinux_packages_schedule: '0 */3 * * *'
# mxlinux_iso_schedule: '0 3 * * *'
# ubuntu_archive_schedule: '0 */6 * * *'
# ubuntu_cdimage_schedule: '0 4 * * *'
# ubuntu_release_schedule: '0 */4 * * *'
# ubuntu_ports_schedule: '0 */6 * * *'
# ubuntu_cloudimage_dir: '0 5 * * *'
# linuxmint_packages_schedule: '0 6,12 * * *'
# linuxmint_iso_schedule: '0 7 * * *'

caddy_config_mode: Caddyfile
caddy_caddyfile: |
  root * {{ lcmirror_root }}
  file_server browse
